version: '3.2'

services:
  court_of_justice_scheme_bot:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - ../../..:/app
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - internal

networks:
  internal:
    external: false
